
# This makefile contains a rule for each test case we would
# like to report in the TeX document and that shows that requirements
# are met.
#

very-first:
	echo 'Very first dataset'
	swipl --quiet --nodebug -t 'go(Schedule).' scheduler.prolog very-first-dataset.prolog
